# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('description', models.CharField(default=None, max_length=200, null=True, verbose_name='项目描述')),
                ('item_name', models.CharField(default=None, max_length=500, null=True, verbose_name='项目映射值')),
                ('max_key', models.CharField(default='0', max_length=50, verbose_name='当前最大key值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItemValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50, verbose_name='记录的key值')),
                ('values', models.CharField(db_index=True, default=' ', max_length=1000, verbose_name='记录值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('pro_name', models.ForeignKey(help_text='项目基础信息表外键', on_delete=django.db.models.deletion.CASCADE, related_name='pro_info', to='initdata.ProjectBaseInfo')),
            ],
        ),
    ]
